name: aw139_cruise
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  fl_chart: ^1.1.1
  http: ^1.5.0
  geolocator: ^14.0.2
  pdf: ^3.11.0
  printing: ^5.12.0
  share_plus: ^12.0.0
  url_launcher: ^6.3.0

  # Map package replacements
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf